version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --init
      - run:
          name: Bundle Install
          command: bundle install --path vendor/bundle
      - run:
          name: Test Git Submodule Checked Out
          command: test -e shindan/Gemfile
